vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set inccommand=split")
vim.cmd("set spell")
vim.cmd("set spelllang=en_ca")
vim.cmd("set clipboard=unnamedplus")
vim.g.mapleader = ","
vim.keymap.set("n", "<leader>s", "<cmd>split<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>v", "<cmd>vsplit<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>nt", "<cmd>tabnew<CR>", { desc = 'New tab', noremap = true, silent = true })
vim.keymap.set("n", "<leader>ns", "<cmd>tabnew | terminal<CR>", { desc = 'New shell', noremap = true, silent = true })
